# Generated by Django 2.2.3 on 2019-08-19 06:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('massage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='relatedUser',
        ),
        migrations.AddField(
            model_name='messages',
            name='relatedUser',
            field=models.ManyToManyField(related_name='Messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
