# Generated by Django 2.2.3 on 2019-08-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massage', '0002_auto_20190819_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='massanger',
            name='token',
            field=models.CharField(default='', max_length=500),
        ),
    ]
